"""add_cubiculos_and_cubiculo_id

Revision ID: 385ac496ca63
Revises: 932518694419
Create Date: 2026-03-08 20:20:39.164784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385ac496ca63'
down_revision: Union[str, None] = '932518694419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cubiculos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cubiculos_slug'), 'cubiculos', ['slug'], unique=True)
    op.add_column('cash_register', sa.Column('cubiculo_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_cash_register_cubiculo_id'), 'cash_register', ['cubiculo_id'], unique=False)
    op.create_foreign_key(None, 'cash_register', 'cubiculos', ['cubiculo_id'], ['id'])
    op.add_column('game_loans', sa.Column('cubiculo_id', sa.Uuid(), nullable=False))
    op.add_column('game_loans', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_game_loans_cubiculo_id'), 'game_loans', ['cubiculo_id'], unique=False)
    op.create_foreign_key(None, 'game_loans', 'cubiculos', ['cubiculo_id'], ['id'])
    op.add_column('games', sa.Column('cubiculo_id', sa.Uuid(), nullable=False))
    op.add_column('games', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_games_cubiculo_id'), 'games', ['cubiculo_id'], unique=False)
    op.create_foreign_key(None, 'games', 'cubiculos', ['cubiculo_id'], ['id'])
    op.add_column('print_balance', sa.Column('cubiculo_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('print_balance_student_id_period_key'), 'print_balance', type_='unique')
    op.create_index(op.f('ix_print_balance_cubiculo_id'), 'print_balance', ['cubiculo_id'], unique=False)
    op.create_unique_constraint(None, 'print_balance', ['student_id', 'cubiculo_id', 'period'])
    op.create_foreign_key(None, 'print_balance', 'cubiculos', ['cubiculo_id'], ['id'])
    op.add_column('print_history', sa.Column('cubiculo_id', sa.Uuid(), nullable=False))
    op.add_column('print_history', sa.Column('period', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_print_history_cubiculo_id'), 'print_history', ['cubiculo_id'], unique=False)
    op.create_foreign_key(None, 'print_history', 'cubiculos', ['cubiculo_id'], ['id'])
    op.add_column('products', sa.Column('cubiculo_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_products_cubiculo_id'), 'products', ['cubiculo_id'], unique=False)
    op.create_foreign_key(None, 'products', 'cubiculos', ['cubiculo_id'], ['id'])
    op.add_column('sales', sa.Column('cubiculo_id', sa.Uuid(), nullable=False))
    op.add_column('sales', sa.Column('cash_register_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_sales_cubiculo_id'), 'sales', ['cubiculo_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'cubiculos', ['cubiculo_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'cash_register', ['cash_register_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_cubiculo_id'), table_name='sales')
    op.drop_column('sales', 'cash_register_id')
    op.drop_column('sales', 'cubiculo_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_cubiculo_id'), table_name='products')
    op.drop_column('products', 'cubiculo_id')
    op.drop_constraint(None, 'print_history', type_='foreignkey')
    op.drop_index(op.f('ix_print_history_cubiculo_id'), table_name='print_history')
    op.drop_column('print_history', 'period')
    op.drop_column('print_history', 'cubiculo_id')
    op.drop_constraint(None, 'print_balance', type_='foreignkey')
    op.drop_constraint(None, 'print_balance', type_='unique')
    op.drop_index(op.f('ix_print_balance_cubiculo_id'), table_name='print_balance')
    op.create_unique_constraint(op.f('print_balance_student_id_period_key'), 'print_balance', ['student_id', 'period'], postgresql_nulls_not_distinct=False)
    op.drop_column('print_balance', 'cubiculo_id')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_index(op.f('ix_games_cubiculo_id'), table_name='games')
    op.drop_column('games', 'is_active')
    op.drop_column('games', 'cubiculo_id')
    op.drop_constraint(None, 'game_loans', type_='foreignkey')
    op.drop_index(op.f('ix_game_loans_cubiculo_id'), table_name='game_loans')
    op.drop_column('game_loans', 'notes')
    op.drop_column('game_loans', 'cubiculo_id')
    op.drop_constraint(None, 'cash_register', type_='foreignkey')
    op.drop_index(op.f('ix_cash_register_cubiculo_id'), table_name='cash_register')
    op.drop_column('cash_register', 'cubiculo_id')
    op.drop_index(op.f('ix_cubiculos_slug'), table_name='cubiculos')
    op.drop_table('cubiculos')
    # ### end Alembic commands ###
