"""add_managed_cubiculo_to_user

Revision ID: 39977d47e771
Revises: 36a3d131fde1
Create Date: 2026-03-08 21:04:26.354238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39977d47e771'
down_revision: Union[str, None] = '36a3d131fde1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('managed_cubiculo_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'cubiculos', ['managed_cubiculo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'managed_cubiculo_id')
    # ### end Alembic commands ###
