"""add_instructions_url_to_games

Revision ID: c6cc6691a719
Revises: 39977d47e771
Create Date: 2026-03-08 21:25:33.509439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6cc6691a719'
down_revision: Union[str, None] = '39977d47e771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('instructions_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'instructions_url')
    # ### end Alembic commands ###
