"""add_service_flags_to_cubiculo

Revision ID: 36a3d131fde1
Revises: 385ac496ca63
Create Date: 2026-03-08 20:33:10.154547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a3d131fde1'
down_revision: Union[str, None] = '385ac496ca63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('cubiculos', sa.Column('games_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('cubiculos', sa.Column('printing_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('cubiculos', sa.Column('products_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cubiculos', 'products_enabled')
    op.drop_column('cubiculos', 'printing_enabled')
    op.drop_column('cubiculos', 'games_enabled')
    # ### end Alembic commands ###
